### ISSUE TITLE
技術選定を行う

### ISSUE THREAD

**Issue by rosh-1228** [rosh-1228/fjord-boot-camp-contributors#12]
サーバーなど選定

**Comment by rosh-1228** [comment]
随時更新
費用は安く => 無料であればありがたい
- ドメイン : [freenom](https://www.freenom.com/ja/index.html?lang=ja)
- ホスティング : [heroku](https://jp.heroku.com/free)
- CDN : [Netlify](https://www.netlify.com/)
- バックエンド : Rails
- フロントエンド: React + Redux

**Comment by rosh-1228** [comment]
1. FBCCのユーザーコミット一覧ページにて、ハッシュボタンをクリックしたときにGithubリポジトリのコミットページへリンクさせますでしょうか？
参考とするRailsContributorはそれぞれリンクを関連づけておりますが、今回作成するFjordBootCampでも、リンクは必要になりますか？
![名称未設定_key](https://user-images.githubusercontent.com/64620506/185307453-815dbdaa-eba6-4957-9725-5e46cbc27099.png)

**Comment by rosh-1228** [comment]
2. FBCCのユーザーの使用する技術とサーバー構成について

使用する技術は以下としたいと考えております。
FrontEnd: React + Redux
BackEnd: Rails + GraphQL
DB: Postgresql

FrontEndはVue.jsを悩んだのですが、調べるとReactは単方向データバインディングを行うとのことでした。
FBCCはgetしか行わないサービスですので、Reactが良いのかな？と思いました。


![名称未設定_key](https://user-images.githubusercontent.com/64620506/185307653-59b241d6-702b-46f0-ab9c-f21d44953575.png)



サーバーの構成も、現時点でこうしたいなというものがありまして、HerokにRails、CDNにNetlifyを使って、ユーザーに静的ページを返すようにし、ある程度サクサク動かせるようにしたいと考えていますが、構成としてこのような形でも良いでしょうか？
![名称未設定_key](https://user-images.githubusercontent.com/64620506/185307582-f423d024-0b55-473c-bf7b-92f2642b07e0.png)

**Comment by rosh-1228** [comment]
3.ドメインについて
 freenomで無料のドメインを使ってもよろしいでしょうか？
 それとも、お名前.comなどで1円でも良いので、購入した方が良いでしょうか？
 突然使えなくなることを考えると有料の方が良いということであれば、購入したいと考えております。

**Comment by komagata** [comment]
@rosh-1228 

> FBCCのユーザーコミット一覧ページにて、ハッシュボタンをクリックしたときにGithubリポジトリのコミットページへリンクさせますでしょうか？

はい。

> FrontEndはVue.jsを悩んだのですが、調べるとReactは単方向データバインディングを行うとのことでした。
> FBCCはgetしか行わないサービスですので、Reactが良いのかな？と思いました。

VueとReactは役割似た様なものなので好みで選んでいいと思います。

> HerokにRails、CDNにNetlifyを使って、ユーザーに静的ページを返すようにし、ある程度サクサク動かせるようにしたいと考えていますが、構成としてこのような形でも良いでしょうか？

@rosh-1228 さんのポートフォリオなのでダメということはできないですが、複数のサービスにフロントエンドとバックエンドを分けるとデプロイなど運用がとても煩雑になるのでお勧めしないです。「なぜわざわざ複数のサービスにデプロイする構成にしたんですか？」と聞かれた時に合理的な返答ができない気がします。

> 3.ドメインについて

herokuであればデフォルトで割り当てられるドメインでいいのではないでしょうか。

**Comment by rosh-1228** [comment]
@komagata 
ご回答ありがとうございます!

> VueとReactは役割似た様なものなので好みで選んでいいと思います。

承知しました！Reactでしたいと思います！

> @rosh-1228 さんのポートフォリオなのでダメということはできないですが、複数のサービスにフロントエンドとバックエンドを分けるとデプロイなど運用がとても煩雑になるのでお勧めしないです。「なぜわざわざ複数のサービスにデプロイする構成にしたんですか？」と聞かれた時に合理的な返答ができない気がします。

たしかに運用は難しそうですね。。
herokuの中でできそうなものを調べたいと思います。

> herokuであればデフォルトで割り当てられるドメインでいいのではないでしょうか。

たしかに、herukappというのが確かありましたね😅
こちらのドメインを使おうと思います！

**Comment by rosh-1228** [comment]
ホスティングサービス(PaaS)は、操作（デプロイ）などのしやすさから、`railway`にした。
バッチ処理(githubリポジトリからコントリビュータとコミットを取得する処理)をgithub actionsで実装

**Comment by rosh-1228** [comment]
選定は終了したので、closeします。
