### ISSUE TITLE
URI設計

### ISSUE THREAD

**Issue by rosh-1228** [rosh-1228/fjord-boot-camp-contributors#14]

**Comment by rosh-1228** [comment]
| method | path | description |
| --- | --- | --- |
| GET | / | 今月のリポジトリに対するコミットランキング画面<br>(this monthを表示)<br>Topページ |
| GET | /contributors/<ユーザー名>/commits | ユーザーのコミット一覧画面 |
| GET | /contributors/all-time | 今までのリポジトリに対するコミットランキング画面 |
| GET | /contributors/today | 今日のリポジトリに対するコミットランキング画面 |
| GET | /contributors/this-week | 今週のリポジトリに対するコミットランキング画面 |
| GET | /contributors/this-month | 今月のリポジトリに対するコミットランキング画面 |
| GET | /contributors/this-year | 今年のリポジトリに対するコミットランキング画面 |
| GET | /contributors/search?name=<検索文字> | ユーザー名検索結果画面 |

**Comment by betachelsea** [comment]
拝見しました！ 👀 

ペーパープロトタイプの画面の様子を拝見すると、this month 自体もリンクはあるようなので、 root のpath ( `/` ) とは別に、this month にもpathを与えておくと管理しやすそうだなと思いましたがいかがでしょう？

root は、ショートカットといいますか、 alias のように働くと考えたほうが便利かなと感じました。

**Comment by rosh-1228** [comment]
ありがとうございます！
たしかに、monthが`/`だけだとわからなくなりますね😅

こちらthis-monthのリソースを追加しました。

**Comment by betachelsea** [comment]
追加ありがとうございます！ 良さそうだと思いました 🙆
