### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by rosh-1228** [rosh-1228/fjord-boot-camp-contributors#15]

**Comment by rosh-1228** [comment]
# ER図
![Image](https://user-images.githubusercontent.com/64620506/183854525-403717ca-6b8c-4fdf-b836-95a6bf07f50c.png)

**Comment by betachelsea** [comment]
拝見しました！ ログインとかがないので、かなりシンプルですね 👍 
自分がちょっとGitHubのAPIまで詳しくないので、推測も含めたレビューになります :pray: 

# Contributorsテーブルについて
- name ですが、アカウント系は表記名とauthorの表記(例えばTwitterでいう表示名 "やまだ" とスクリーンネーム `@yamada` など)があったりするので、その辺りはGitHubのAPIを調べつつ、どう保持するかを考える必要はありそうです。
- GitHubが持っているid的なものがあれば、それを保持するカラムを持つ必要が発生する可能性が高そうだと思いました。
- commit_since には日付が入りそうですね。Railsで作る場合、日付系の カラムは `_on`、日時は `_at` を末尾につける習慣が多いです。必ずそうしなければいけないというわけではありませんが、参考まで。  (以下・例)
  - 作成日「2022/08/16」を保持したい場合、`created_on`
  - 作成日時 「2022/08/16 12:00:00」を保持したい場合、 `created_at`


# Contributors_commits テーブルについて
- テーブル名ですが、このサービスはContributorsのものを扱うということが自明なので、シンプルに「Commits」テーブルという名前でも十分伝わるのではと感じました。
- こちらの commit_date についても、 `_on` , `_at` の表記ルールを適用しても良さそうだと思いました。

# 気になること・数のキャッシュ
おそらく、最初の方は都度SQLを発行しても十分問題なく一覧を取得できると思うのですが、
データが増えれば増えるほど、COUNTしてそれをもとに並び替えた情報を返す処理に時間がかかっていく可能性が高そうです。
将来的に、カラムに合計値(全てのcommitの数、今日のcommitの数、今週のcommitの数、今年のcommitの数) をそれぞれ持たせて、特定のタイミングで更新をかけるといった運用が必要になりそうだと考えました。(最初から対応するか、将来的に問題に直面したら検討するかについては、おまかせします 🙏  )


# 質問・ランキング表記について
ペーパープロトタイプで、`#1` という表記がありましたが、それはどのような処理で表示させる予定でしょうか？  参考にしてるRailsのランキングでは、All time の並びに従って `#1` などがついて、他のページではそれを表示しているようですね。 こちらももしやってみて処理が重たいとなれば、カラムとして値を保持するのを検討する必要が発生しそうだなと思いました。

# 質問・検索について
あくまでもユーザー名のみの検索のみ対応という認識で良いでしょうか？
他に検索させたい内容があれば、DBの方に工夫を入れる必要があったりしそうです。

**Comment by rosh-1228** [comment]
レビューありがとうございます！
# Contributorsテーブルについて
> name ですが、アカウント系は表記名とauthorの表記(例えばTwitterでいう表示名 "やまだ" とスクリーンネーム @yamada など)があったりするので、その辺りはGitHubのAPIを調べつつ、どう保持するかを考える必要はありそうです。

githubには名前が2つあるということは承知しております。
https://github.com/の次に来るログイン名を取得したいと考えております。
理由として、メンション時などログイン名を使っており、認知度としてはログイン名の方があると思ったからです。

> GitHubが持っているid的なものがあれば、それを保持するカラムを持つ必要が発生する可能性が高そうだと思いました。

申し訳ありません💦
idが必要な理由がわからず、どういう意図があるのか教えてください🙇‍♂️

[githubのGraphQL APIのリファレンス](https://docs.github.com/ja/graphql/reference/objects#user)でUserから取得できるようなidがdatabaseIdがとれるので、取得してみましたが、`"databaseId": 16577`や`"databaseId":  3379823`のようなidで、githubが持つDatabaseのidといった感じでした。


> commit_since には日付が入りそうですね。Railsで作る場合、日付系の カラムは _on、日時は _at を末尾につける習慣が多いです。必ずそうしなければいけないというわけではありませんが、参考まで。 (以下・例)
作成日「2022/08/16」を保持したい場合、created_on
作成日時 「2022/08/16 12:00:00」を保持したい場合、 created_at

こちらは`commited_on`に修正したいと思います！

# Contributors_commits テーブルについて
> テーブル名ですが、このサービスはContributorsのものを扱うということが自明なので、シンプルに「Commits」テーブルという名前でも十分伝わるのではと感じました。

こちらCommitsに修正します！

> こちらの commit_date についても、 _on , _at の表記ルールを適用しても良さそうだと思いました。

こちらも修正します！

# 気になること・数のキャッシュ
> おそらく、最初の方は都度SQLを発行しても十分問題なく一覧を取得できると思うのですが、
データが増えれば増えるほど、COUNTしてそれをもとに並び替えた情報を返す処理に時間がかかっていく可能性が高そうです。
将来的に、カラムに合計値(全てのcommitの数、今日のcommitの数、今週のcommitの数、今年のcommitの数) をそれぞれ持たせて、特定のタイミングで更新をかけるといった運用が必要になりそうだと考えました。(最初から対応するか、将来的に問題に直面したら検討するかについては、おまかせします 🙏 )

確かに、DBにあった方が毎回の計算がなくなるので、計算処理が軽くなりそうだと思いました！
こちら修正します！


# 質問・ランキング表記について

> ペーパープロトタイプで、#1 という表記がありましたが、それはどのような処理で表示させる予定でしょうか？ 参考にしてるRailsのランキングでは、All time の並びに従って #1 などがついて、他のページではそれを表示しているようですね。 こちらももしやってみて処理が重たいとなれば、カラムとして値を保持するのを検討する必要が発生しそうだなと思いました。

フロントエンド側で計算して表示しようかなと考えておりましたが、これから先contributorが増えるとなれば確かに重たくなってきそうですね😓
そこまで考えられてなかったです。。。
ありがとうございます！カラムとしてrankをcontributorsに追加し、バックエンドでcommitsテーブルからデータを取得・計算し、contributorsテーブルをupdateしようと思います！

# 質問・検索について
> あくまでもユーザー名のみの検索のみ対応という認識で良いでしょうか？
他に検索させたい内容があれば、DBの方に工夫を入れる必要があったりしそうです。

はい。ユーザー名のみを想定しております。

**Comment by rosh-1228** [comment]
レビューコメントをもとに修正しました！
ご確認お願いします！

![fix-fjordcontributors drawio](https://user-images.githubusercontent.com/64620506/185059871-c311a89d-c524-4777-95a1-5b3e1cf2c5e6.png)

**Comment by betachelsea** [comment]
諸々回答・修正ありがとうございます！良いと思いました :ok_person: 


###  idが必要な理由

自分がidを必要だと思うのは、usernameはユーザが自由に変更できてしまうためです。
サービスの中で一意としてつかうキーが利用者によって自由に変更できる場合、同一データであることを判断するためのよすがとして、idを利用することになります。今回書いていただいた databaseId が、おそらくそうかなと思いました。
ただ、commit でうまくdatabaseIdと紐づいていない値もあるかも(※)しれず、なかなか変える人はいないと割り切って、username( https://github.comの次にくるログイン名 ) をキーにするのも判断のひとつかなと思います。 :eyes:   一意見まで :pray: 

※管理されるcommitの中には、GitHubのアカウントを持たない利用者によるcommitも存在しうる。そのようなcommitの情報をとってきた場合、GitHubのdatabaseId は付与されないのではないか、と予想しました。

###  (強いて言えば)  ***_commits 、 all-time のカラムについて

commits というテーブルが存在するので、`today_commits` などの命名だと、(Railsの場合) Commit のインスタンスの配列が得られそうだな〜という印象がありました。 :eyes: 　また、 `all-time` も、サービス全体を見ると 全部を通してのコミット数ということは自明ですが、単語単位でみるとどんな値が返ってくるのか予想が難しいと感じました。( *あれ、ハイフンってカラム名に入れられましたっけ...もしかするとハイフンは不都合になるシーンがあるかもしれないです。Rubyがハイフン含む命名とは、少し相性が悪いので。 )


シンプルなER図ですし、質問への回答もいただいたので、致命的な問題はないと判断し、確認OKとさせてもらいます :ok_person: 
ただし、おそらくサービスを作っていく過程で「やっぱり〇〇が欲しかった」「〇〇は必要なかった」という判断に出会っていくので、そういう場合は、「このissueでOKをもらったから変更しない」とせず、積極的にサービスの求める形に応じて修正を加えていただければと思います！ :+1:  (もちろん、リリース後は、カラムの修正は慎重に... でもまぁリリース前なら大胆にやってもまぁ大丈夫かな、と！) 

サービス作りファイトです！ :rocket:

**Comment by rosh-1228** [comment]
@betachelsea 
ご確認ありがとうございます！

## idが必要な理由
こちらについてご教示ありがとうございます！
確かに、今後ログイン名を変更される方もいらっしゃるかもしれないというところまで気が回っておりませんでした💦

注意書きの箇所にもあるようなアカウントを持たない利用者というのも想定した場合、元のサイトの[Rails Contributor](https://contributors.rubyonrails.org/)では、全てに名前があったりすることから、username( [https://github.comの次にくるログイン名](https://github.xn--com-373btfra9rlh3dv2aec9554dgyyc/) )をキーにしたいと思います！

## (強いて言えば) ***_commits 、 all-time のカラムについて
確かにcommitsテーブルがあるので、そちらからインスタンスの配列が得られそうだなとも思ったのですが、思いつかず***_commitsという名前にしました😓

例えば、***_commit_countなどのような名前でも同じように感じるでしょうか？？

all-timeは、`all_time_commits`に修正しようと思います！




> ただし、おそらくサービスを作っていく過程で「やっぱり〇〇が欲しかった」「〇〇は必要なかった」という判断に出会っていくので、そういう場合は、「このissueでOKをもらったから変更しない」とせず、積極的にサービスの求める形に応じて修正を加えていただければと思います！ 👍 (もちろん、リリース後は、カラムの修正は慎重に... でもまぁリリース前なら大胆にやってもまぁ大丈夫かな、と！)

ありがとうございます！
作りながら修正あれば、相談しながら進めていきたいと思います💪💪

**Comment by rosh-1228** [comment]
また、[commitされたコードのページが必要になりました](https://github.com/rosh-1228/fjord-boot-camp-contributors/issues/12#issuecomment-1219235449)ので、Contributorsテーブルに1つcommit_urlというカラムを追加しております。

**Comment by rosh-1228** [comment]
![fjordcontributors drawio (1)](https://user-images.githubusercontent.com/64620506/185581665-ed309906-365b-46c3-b8b1-c4bff483222d.png)

**Comment by betachelsea** [comment]
修正ありがとうございます！ 👍  

> 例えば、***_commit_countなどのような名前でも同じように感じるでしょうか？？

自分は count が入っていたらカウント数かなと思えると感じました！ (個々のメンター毎に意見が違うと思うので、もし今後「これだ！」と思える意見に出会ったら気にせず変更してくださいね！ 🙏  )

> commitされたコードのページが必要になりました

`commit_url` は、commit毎に発生するものかなと思いましたがどうでしょう？ 
その場合は、Contributors ではなくCommits テーブルにあるのが自然ですね。
また、hash があれば取得してこれる気がしましたがどうでしょうか？

適当に https://github.com/fjordllc/bootcamp の最新3つのcommit URLを抽出してきました。

- `https://github.com/fjordllc/bootcamp/commit/2b9cd7b9d579f0cae4a5098381d00b6be2276d3a`
- `https://github.com/fjordllc/bootcamp/commit/187fcf35a48a8c3dc065e62caee1fee5b6578853`
- `https://github.com/fjordllc/bootcamp/commit/57c4f35c6b9a64f0876bcc6a552f0af107151c66`

前半は固定値として "https://github.com/fjordllc/bootcamp/commit/" を入れ、その後にhash を与えてやると閲覧できそうです :eyes: 

もし、他のいろんなリポジトリを相手にデータを取ってくる場合は、URL自体を保持した方が良いかもしれませんが、 https://github.com/fjordllc/bootcamp  のリポジトリのみをターゲットにする場合は、上記の戦略でも問題なさそうです 👀

**Comment by rosh-1228** [comment]
> commit_url は、commit毎に発生するものかなと思いましたがどうでしょう？
その場合は、Contributors ではなくCommits テーブルにあるのが自然ですね。
また、hash があれば取得してこれる気がしましたがどうでしょうか？

たしかに、固定値となるURLの後ろにハッシュを入れても良いですね！

> もし、他のいろんなリポジトリを相手にデータを取ってくる場合は、URL自体を保持した方が良いかもしれませんが、 https://github.com/fjordllc/bootcamp のリポジトリのみをターゲットにする場合は、上記の戦略でも問題なさそうです 👀

ありがとうございます。私の方でも考えましたが、この通りにしたほうがテーブルもすっきりしそうなので、commit_urlだけはなかったことにします😃

**Comment by rosh-1228** [comment]
> 自分は count が入っていたらカウント数かなと思えると感じました！ (個々のメンター毎に意見が違うと思うので、もし今後「これだ！」と思える意見に出会ったら気にせず変更してくださいね！ 🙏 )

ありがとうございます！
良いものがあればそちらに変更したいと思います！

**Comment by rosh-1228** [comment]
現段階では、こちらのER図を元に進めていくことにします！
![fjordcontributors_drawio_-_diagrams_net](https://user-images.githubusercontent.com/64620506/185736313-ade3e22f-0e49-4426-a590-872721593b61.png)
